remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/image/Imagen lk-modified.png
description: Ingeniero en inform√°tica | Analista de datos
github:
  is_project_page: false

plugins:
- jekyll-remote-theme



